CU-2veea54 Create partners component
tul-ftims-students-council/Delta pull request #5
Opened 2022-09-19 18:13 UTC by OlaMikolajczyk

2022-09-19 18:13 UTC, pmakowski23 commented
Task linked: [CU-2veea54 Partners](https://app.clickup.com/t/2veea54)

2022-09-20 19:21 UTC, d-wasilewski requested changes

2022-09-20 19:21 UTC, d-wasilewski commented on src/components/Partners.astro
> +</head>
Move it to `<head>` in [Layout.astro](https://github.com/tul-ftims-students-council/Delta/blob/master/src/layouts/Layout.astro)

2022-09-20 19:21 UTC, d-wasilewski commented on src/components/Partners.astro
> +            <img src="/Users/olcia/VSC Delta/Delta/public/assets/partners/Commerzbank.png" height="50" width="381"/>
`/assets/partners/file.png` is enough for the file to be resolved

2022-09-20 19:21 UTC, d-wasilewski commented on src/components/Partners.astro
> +    font-family: 'Inter', sans-serif; /* help */
👍

2022-09-20 19:21 UTC, d-wasilewski commented on src/components/Partners.astro
> +    }
Duplicate of [this](https://github.com/tul-ftims-students-council/Delta/blob/master/src/styles/lemonmilk.css)

2022-09-21 16:04 UTC, d-wasilewski approved these changes

2022-09-21 18:59 UTC, pmakowski23 approved these changes

2022-09-21 19:00 UTC, merged