CU-2vee8bh Register Page
tul-ftims-students-council/Delta pull request #8
Opened 2022-09-21 16:13 UTC by d-wasilewski

TODO

- Try to produce an error when emails aren't the same
- replace plain colors with variables
- clean unnecessary things (form-related mostly)
- merge with layout

2022-09-21 16:13 UTC, pmakowski23 commented
Task linked: [CU-2vee8bh Register Page](https://app.clickup.com/t/2vee8bh)

2022-09-22 19:04 UTC, pmakowski23 commented on src/pages/index.astro
> +  <RegisterForm client:only="solid-js"/>
Please render it on separate page and add button in header that will lead to registration.

2022-09-26 08:55 UTC, pmakowski23 requested changes
Please improve responsiveness

2022-09-26 18:16 UTC, pmakowski23 approved these changes
Good job!

2022-09-27 14:33 UTC, kwawrzynczak approved these changes

2022-09-27 14:35 UTC, merged